{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "0ab20dcf_806c2c97",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-09T23:48:37Z",
      "side": 1,
      "message": "Script failing with USB OTG wireless input receiver, and the device is being detected during boot.",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f0fdb480_4693ce54",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T00:52:33Z",
      "side": 1,
      "message": "The script fails because the post-fs hasn\u0027t run yet to set the proper permissions on the usb_data_enabled file. We run the script as nobody:system, and usb_data_enabled is not yet set up for that. This wasn\u0027t an issue with `onrestart` because the `write` builtin presumably because init has access to do this just fine.\n\nI tried using init\u0027s `file` command to pass a read-write file descriptor, but that didn\u0027t work out (comlicated, still an selinux nightmare, no permission).",
      "parentUuid": "0ab20dcf_806c2c97",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "8ce091cb_372a29b4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T00:58:18Z",
      "side": 1,
      "message": "Something may have changed, perhaps since Android 13, because even using `write` for this doesn\u0027t work now in early-init:\n`[    1.192675] audit: type\u003d1400 audit(1704847988.088:4): avc:  denied  { write } for  pid\u003d1 comm\u003d\"init\" name\u003d\"usb_data_enabled\" dev\u003d\"sysfs\" ino\u003d813\n26 scontext\u003du:r:init:s0 tcontext\u003du:object_r:sysfs:s0 tclass\u003dfile permissive\u003d0`",
      "parentUuid": "f0fdb480_4693ce54",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "aeae89d4_e4ce041e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T01:12:00Z",
      "side": 1,
      "message": "If I try to fix the owner and mode of the file at the top of /system/core/rootdir/init.rc for testing, that fails due to selinux, too (too early). But if I set the user for this to `root`, the script succeeds, so I suspect it actually writes. The problem is that even though the script succeeds, USB is not ejected (the receiver is still seen).\n\nYou can even test by connecting the device with USB debugging, and set the value manually with adb. You can check that it\u0027s disabled, but you\u0027re still connected. So at least now, on some devices, setting usb_data_enabled does not lead to an immediate ejection of USB devices. That\u0027s the current problem, and the continuing problem. We don\u0027t want users to be affected if they start up their phones while connected to an untrusted device.",
      "parentUuid": "8ce091cb_372a29b4",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "9e767977_c76d3033",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T14:33:24Z",
      "side": 1,
      "message": "Ack, these issues are resolved in latest patchset (alongside other needed patches).",
      "parentUuid": "aeae89d4_e4ce041e",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "dacec50e_78932a5c",
        "filename": "usb/gadget/android.hardware.usb.gadget-service.rc",
        "patchSetId": 1
      },
      "lineNbr": 24,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T01:16:31Z",
      "side": 1,
      "message": "Try changing disable_usb_data so it does the same thing as enable_usb_data from [here](https://review.calyxos.org/c/CalyxOS/device_google_gs101/+/24087/1), except toggle every 1 and 0. Changing the OTG state seems to \"eject\" the USB device - I think.",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4abb0a64_02a0f48e",
        "filename": "usb/gadget/android.hardware.usb.gadget-service.rc",
        "patchSetId": 1
      },
      "lineNbr": 24,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T01:19:57Z",
      "side": 1,
      "message": "1. The Logitech USB receiver does not show up. Good!\n2. Plugging in to a computer, USB debugging starts up immediately. Bad...",
      "parentUuid": "dacec50e_78932a5c",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "3a992f01_ce882e3a",
        "filename": "usb/gadget/android.hardware.usb.gadget-service.rc",
        "patchSetId": 1
      },
      "lineNbr": 24,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T01:31:31Z",
      "side": 1,
      "message": "My next thought was to change the OTG values to the wrong values and then back to the right ones, hoping that would disconnect the device on the other end but cause usb_data_enabled to start being respected. It does disconnect, but it reconnects shortly after.",
      "parentUuid": "4abb0a64_02a0f48e",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "f5366116_d6c501ff",
        "filename": "usb/gadget/android.hardware.usb.gadget-service.rc",
        "patchSetId": 1
      },
      "lineNbr": 24,
      "author": {
        "id": 1000062
      },
      "writtenOn": "2024-01-10T14:33:24Z",
      "side": 1,
      "message": "Ack, the key was to look at what enableUsbData in Usb.cpp does, because that\u0027s what is ultimately used when changing to Deny usb in Settings, which *does* successfully detach devices and disable data.",
      "parentUuid": "3a992f01_ce882e3a",
      "revId": "be113c92cbc05ef2ad9c8ba62e6d51c44930d53f",
      "serverId": "35266860-6252-469c-a67d-185064479fc0"
    }
  ]
}